version: '2.2'
services:
  governify_electra:
    container_name: governify-electra
    image: isagroup/electra
    environment:
      - NODE_ENV=production
      - PORT=80
    restart: 'on-failure:5'
    ports: 
      - 8080:80