production:
  server: 
    port: 8080
    bypassCORS: true
    useHelmet: true
  app:
    INPUT_SUBFOLDER_NAME: input
    OUTPUT_SUBFOLDER_NAME: output
    PUBLIC_SUBFOLDER_PATH: src/frontend/data
    INPUT_SUBFOLDER_PATH: src/backend/input
    OUTPUT_SUBFOLDER_PATH: src/backend/output
    SELECTED_ANALYSIS_MODULE: module_5
  log:
    level: info
    file: './logs/pro-logs.log' #Where log file will be saved. Date will be concatenated before the name.
    maxSize: 10000000 #(10MB) Maximum file log size, if one file reaches it, a new file is created.
    maxFiles: 30 # Max Files that can be created per day reaching the maxSize.

development:
  server: 
    port: 8080
    bypassCORS: true
    useHelmet: true
  app:
    INPUT_SUBFOLDER_NAME: input
    OUTPUT_SUBFOLDER_NAME: output
    PUBLIC_SUBFOLDER_PATH: src/frontend/data
    INPUT_SUBFOLDER_PATH: src/backend/input
    OUTPUT_SUBFOLDER_PATH: src/backend/output
    SELECTED_ANALYSIS_MODULE: module_5
  log:
    level: debug
    file: './logs/dev-logs.log' #Where log file will be saved. Date will be concatenated before the name.
    maxSize: 10000000 #(10MB) Maximum file log size, if one file reaches it, a new file is created.
    maxFiles: 30 # Max Files that can be created per day reaching the maxSize.

testing:
  server:
    port: 8080
    bypassCORS: true
    useHelmet: true
  app:
    INPUT_SUBFOLDER_NAME: input
    OUTPUT_SUBFOLDER_NAME: output
    PUBLIC_SUBFOLDER_PATH: src/frontend/data
    INPUT_SUBFOLDER_PATH: src/backend/input
    OUTPUT_SUBFOLDER_PATH: src/backend/output
    SELECTED_ANALYSIS_MODULE: module_5

  log:
    file: './logs/test-logs.log' #Where log file will be saved. Date will be concatenated before the name.
    maxSize: 10000000 #(10MB) Maximum file log size, if one file reaches it, a new file is created.
    maxFiles: 30 # Max Files that can be created per day reaching the maxSize.
  
