swagger: '2.0'
info:
  description: >-
    <a target="_blank"
    href="https://documenter.getpostman.com/view/3733329/publicationsdata/RVfwiWME">Postman
    Documentation</a>
  version: 1.0.0
  title: Swagger publications.data.sabius-alpha
  termsOfService: www.isa.us.es
  contact:
    name: ISA Research Group
    url: www.isa.us.es
    email: isagroup.us@gmail.com
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
host: publications.data.sabius-alpha.services.governify.io
basePath: /api
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  '/v1/{snapshot}/authors':
    get:
      tags:
        - authors
      description: search author by ORCID
      operationId: getAuthor
      parameters:
        - name: authorId
          in: query
          description: ORCID or scopusId
          required: true
          type: string
        - name: forceSearch
          in: query
          description: forceSearch no cache
          required: false
          type: boolean
        - name: snapshot
          in: path
          description: The identifier of the snapshot
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: integer
        '400':
          description: Invalid status value
      x-swagger-router-controller: Author
  '/v1/{snapshot}/authors/{authorId}/metrics':
    get:
      tags:
        - authors
      description: Finds metrict of author by orcid
      operationId: getAuthorMetrics
      parameters:
        - name: authorId
          in: path
          description: Tags to filter by
          required: true
          type: string
        - name: snapshot
          in: path
          description: The identifier of the snapshot
          required: true
          type: string
        - name: forceSearch
          in: query
          description: forceSearch no cache
          required: false
          type: boolean
      responses:
        '200':
          description: successful operation
          schema:
            type: object
        '400':
          description: Invalid tag value
      x-swagger-router-controller: Author
  '/v1/{snapshot}/authors/{authorId}/documents':
    get:
      tags:
        - authors
      description: 'Search a documents of the author '
      operationId: getDocumentsByAuthor
      parameters:
        - name: authorId
          in: path
          description: The identifier of the author
          required: true
          type: string
        - name: snapshot
          in: path
          description: The identifier of the snapshot
          required: true
          type: string
        - name: forceSearch
          in: query
          description: forceSearch no cache
          required: false
          type: boolean
      responses:
        '200':
          description: successful operation
          schema:
            type: object
        '400':
          description: Invalid status value
      x-swagger-router-controller: Author
  # '/v1/apikeys':
  #   get:
  #     tags:
  #       - apikeys
  #     description: search author by ORCID
  #     operationId: getApisKeysStats
  #     responses:
  #       '200':
  #         description: successful operation
  #         schema:
  #           type: object
  #       '400':
  #         description: Invalid status value
  #     x-swagger-router-controller: Author
  # '/v1/getAuthorId':
  #   get:
  #     tags:
  #       - authors
  #     description: search scopusId with orcid
  #     operationId: getAuthorId
  #     parameters:
  #       - name: orcid
  #         in: query
  #         description: The identifier of the author
  #         required: true
  #         type: string
  #       - name: forceSearch
  #         in: query
  #         description: forceSearch no cache
  #         required: false
  #         type: boolean
  #     responses:
  #       '200':
  #         description: successful operation
  #         schema:
  #           type: object
  #       '400':
  #         description: Invalid status value
  #     x-swagger-router-controller: Author
