openapi: 3.0.0
servers: []
info:
  description: ''
  version: 1.0.0
  title: s2
  termsOfService: ''
  contact:
    email: ''
  x-sla: './s2-plans.yaml'
paths:
  /api/s2/m1:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: 's2m1'
      responses:
        default:
          description: ''
  /api/s2/m2:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: 's2m2'
      responses:
        default:
          description: ''
  /api/s2/m3:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: 's2m3'
      responses:
        default:
          description: ''
  /api/s2/m4:
    get:
      summary: ''
      description: ''
      parameters: []
      operationId: 's2m4'
      responses:
        default:
          description: ''